# Generated by Django 2.2.11 on 2020-03-26 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fever", models.BooleanField(default=False)),
                ("cough", models.BooleanField(default=False)),
                ("difficult_breathing", models.BooleanField(default=False)),
                ("self_quarantine", models.BooleanField(default=False)),
                ("latitude", models.DecimalField(decimal_places=15, max_digits=18)),
                ("longitude", models.DecimalField(decimal_places=15, max_digits=18)),
                ("creation_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
