# Generated by Django 2.2.11 on 2020-04-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthentry", name="age", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="healthentry",
            name="gender",
            field=models.CharField(
                choices=[("Male", "M"), ("Female", "F")], default="M", max_length=1
            ),
        ),
    ]
