# Generated by Django 2.2.11 on 2020-04-04 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthentry",
            name="cough",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="creation_timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="difficult_breathing",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="fever",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="self_quarantine",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
