# Generated by Django 2.2.11 on 2020-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellnessentry",
            name="latitude",
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wellnessentry",
            name="longitude",
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
