# Generated by Django 2.2.11 on 2020-03-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_auto_20200317_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellnessentry",
            name="self_quarantine",
            field=models.BooleanField(default=False),
        ),
    ]
