# Generated by Django 2.2.11 on 2020-03-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_wellnessentry_self_quarantine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wellnessentry",
            name="latitude",
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name="wellnessentry",
            name="longitude",
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
