# Generated by Django 2.2.11 on 2020-04-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_auto_20200404_2330"),
        ("maps", "0002_auto_20200404_2322"),
    ]

    operations = []
