# Generated by Django 2.2.11 on 2020-03-20 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_auto_20200320_2333"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wellnessentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
