# Generated by Django 2.2.11 on 2020-04-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_merge_20200404_2357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthentry",
            name="age",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="cough",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="difficult_breathing",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="fever",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "M"), ("Female", "F")],
                default="M",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="latitude",
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="longitude",
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="healthentry",
            name="self_quarantine",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
