# Generated by Django 2.2.11 on 2020-04-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0007_auto_20200405_0001"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyValuePair",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("counter", models.CharField(max_length=100)),
            ],
        ),
    ]
