# Generated by Django 2.2.11 on 2020-04-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0008_keyvaluepair"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keyvaluepair", old_name="counter", new_name="value",
        ),
    ]
